name: nexus-oci-upload-workflow
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on:

  workflow_dispatch:
    
jobs:
  upload-image:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
      - name: Register Nexus artifact
        uses: cloudbees-io/register-build-artifact@v2
        with:
          name: mlcb-nexus-test
          version: ${{cloudbees.version}}
          url: nexusoss.saas-preprod.beescloud.com/aspm-test:${{cloudbees.version}}
      - name: Print output parameter artifact ID from Nexus upload action
        uses: docker://alpine:latest
        shell: sh
        run: |
         echo "artifact ID for my-artifact is: ${{ steps.step1.outputs.artifact-id }}"
